export const welcomeLanguages: string[] = [
  "Welcome to Summoner's Rift!",
  "Bem-vindo à Summoner's Rift!",
  "Hoşgeldiniz Sihirdar Vadisi'ne!",
  'Willkommen in der Beschwörerkluft!',
  '¡Bienvenidos a la Grieta del Invocador!',
  "Bienvenue dans la Faille de l'Invocateur !",
  'Benvenuti nella Landa degli evocatori!',
  "Vítejte v Summoner's Rift!",
  "Καλώς ήρθατε στο Summoner's Rift!",
  'Üdvözöllek a Hívók Völgyében!',
  "Witaj w Summoner's Rift!",
  "Bine ați venit în Summoner's Rift!",
  'Добро пожаловать в Ущелье Призывателя!',
  'サモナーズリフトへようこそ！',
  '소환사의 협곡에 오신 것을 환영합니다!',
  '欢迎来到召唤师峡谷！',
];
